### ISSUE TITLE
Add two questions to the form

### ISSUE THREAD

**Issue by EsaMakinen** [futurice/symptomradar#116]
Add these two questions to the form

Ripulia tai vatsakipua
Kyllä / Ei

Hajuaistin tai makuaistin heikkenemistä
Kyllä / Ei

**Comment by siniauer** [comment]
@EsaMakinen should the first one be 
Vatsaoireita kuten ripulia, pahoinvointia tai vatsakipuja  
Kyllä / Ei

(this way maybe easier to understand what kind of stomach aches we are after). Should I check with the university professor?

**Comment by Doniee** [comment]
Any thoughts on the order, after which questions would these go?

**Comment by siniauer** [comment]
After Nuhaa, I'd say.

**Comment by siniauer** [comment]
I think adding stomach pain/diarrhea etc is definitely something we can do, more we ask, more we get :)  In the beginning we were worried not to ask too many things, that's why we narrowed it down so much. But if this doesn't seem too long, let's add both now. Let's remove stomach issues if someone is strongly against it.

**Comment by jareware** [comment]
Added in #119
