### ISSUE TITLE
Provide translations to English & other languages

### ISSUE THREAD

**Issue by deanc** [futurice/symptomradar#118]
There are over 300k people in Finland who can't speak Finnish. It would be good for this (the form embed) to also serve them. I'm happy to help do this if the folks working on this tell me how they'd want to implement it.

**Comment by deanc** [comment]
I'm used to using react etc. so it's quite unusual to see such a raw codebase. That said a quick google served up some very lightweight translation libraries. How about this? http://www.lingumania.com/index.html

Would it be acceptable?

**Comment by EsaMakinen** [comment]
This is definetly something we want to do. English, swedish and other languages as well. We'll have a quick discussion with the team and get right back to you. Thanks for the idea!

**Comment by jareware** [comment]
Hey @deanc, thanks for your offer to help!

We went through this quickly with the dev team, and our current assumption is that the best overall solution would be to move the index HTML to be generated by a template anyway. As it stands, and due to this project being set up in a bit of a rush, it's just static HTML. This poses other challenges to e.g. maintainability - we have TS, but if any fields are added/changed/removed, you just need to remember to update the HTML as well.

The first step in that would be a build script added here:

https://github.com/futurice/symptomradar/blob/0bcf9e4ff121af4f15461f1072f579b848d48f67/frontend/embed/v1/package.json#L22

...which would then output a language-specific version of [the index file](https://github.com/futurice/symptomradar/blob/master/frontend/embed/v1/public/index.html). In practice, the current index file would simply become a template, with the current lang-specific strings replaced with references to a translation file.

Personally I would prefer https://lodash.com/docs/4.17.15#template for this.

This would take us to a sustainable direction both in terms of upcoming features, and performance (static HTML is pretty fast to render).

Does this sound at all like an undertaking you'd be interested in?

**Comment by deanc** [comment]
Yeah I can try and take care of it. Can you do me a favour first? Can you check out the repo from a fresh directory on your computer, run `npm install` in the embed root and then `npm start` and add whatever missing dependencies there are for it to not run on my machine.

I so far had to add at least two typescript packages, and i think it's missing types for uuid too before I gave up. Once it's running freshly I can tackle it tomorrow probably :)

**Comment by EsaMakinen** [comment]
I've now created a project for this: https://github.com/futurice/symptomradar/projects/7

**Comment by EsaMakinen** [comment]
Hi @deanc this is closing to go to production: https://github.com/futurice/symptomradar/pull/178

**Comment by jareware** [comment]
Done & shipped!
